spring:
    jackson:
        property-naming-strategy: SNAKE_CASE

url-configuration:
    base-spotify-url: "https://api.spotify.com/v1/"
    spotify-auth-url: "https://accounts.spotify.com/"
    base-application-url: "http://localhost:8080/"